init project
t-t-h-q/OnlineDoctorFE pull request #1
Opened 2024-10-09 08:34 UTC by trinhdinhhiep

- init project
- config ESLint, Prettier, husky

2024-10-09 15:15 UTC, tuev commented on .gitignore
> +*.suo
??

2024-10-09 15:15 UTC, tuev commented on .gitignore
> +*.ntvs*
remove all unused type

2024-10-09 15:16 UTC, tuev commented on .husky/pre-commit
> +yarn check:all
should add linting for pre-commit in husky

2024-10-09 15:33 UTC, trinhdinhhiep commented on .husky/pre-commit
> +yarn check:all
yarn check:all includes: linting check, Prettier check, and type check.

2024-10-10 03:21 UTC, vuquangit commented
Change npm to pnpm

2024-10-10 04:22 UTC, vuquangit commented on yarn.lock
remove this file

2024-10-11 07:44 UTC, mrbin264 commented on .husky/pre-commit
> +yarn check:all
Why is "yarn check:all" being used when the project has switched to pnpm?

2024-10-11 10:20 UTC, tuev requested changes

2024-10-11 10:20 UTC, tuev commented on .prettierrc
> +  "trailingComma": "none",
should use trailing comma

2024-10-11 10:20 UTC, tuev commented on eslint.config.js
> +      "prettier/prettier": [
duplicate with pretierrc

2024-10-11 10:20 UTC, tuev commented on src/index.css
> +:root {
need add normalizecss

2024-10-11 10:20 UTC, tuev commented on tsconfig.app.json
> +{
why do we need tsconfig.app and tsconfig.node

2024-10-11 10:38 UTC, trinhdinhhiep commented on tsconfig.app.json
> +{
Vite creates tsconfig.app and tsconfig.node to optimize TypeScript compilation for browser and Node.js environments, respectively. This separation prevents conflicts and improves build performance.

2024-10-11 11:20 UTC, trinhdinhhiep commented on src/index.css
> +:root {
done

2024-10-12 05:02 UTC, tuev approved these changes
LGTM

2024-10-12 07:10 UTC, vuquangit approved these changes

2024-10-12 09:07 UTC, mrbin264 approved these changes

2024-10-12 11:01 UTC, merged